BASEDIR	:= $(dir $(firstword $(MAKEFILE_LIST)))
VPATH	:= $(BASEDIR)

#---------------------------------------------------------------------------------
# Build options
#---------------------------------------------------------------------------------
TARGET  = libSDL2_image.a
SOURCES = \
	IMG.c \
	IMG_bmp.c \
	IMG_gif.c \
	IMG_jpg.c \
	IMG_lbm.c \
	IMG_pcx.c \
	IMG_png.c \
	IMG_pnm.c \
	IMG_svg.c \
	IMG_tga.c \
	IMG_tif.c \
	IMG_webp.c \
	IMG_WIC.c \
	IMG_xcf.c \
	IMG_xpm.c \
	IMG_xv.c \
	IMG_xxx.c

OBJECTS = $(shell echo $(SOURCES) | sed -e 's,\.c,\.o,g')
INCLUDE = -I$(WUT_ROOT)/include -I$(PORTLIBS)/include -I$(BASEDIR)/../SDL2-wiiu/include

#---------------------------------------------------------------------------------
# Compile flags
#---------------------------------------------------------------------------------
BUILDFLAGS	+=	-DLOAD_BMP -DLOAD_GIF -DLOAD_LBM -DLOAD_PCX -DLOAD_PNM \
				-DLOAD_SVG -DLOAD_TGA -DLOAD_XCF -DLOAD_XPM -DLOAD_XV \
				-DLOAD_JPG -DLOAD_PNG
CFLAGS		+=	-O2 $(BUILDFLAGS) $(INCLUDE)
CXXFLAGS	+=	-O2 $(BUILDFLAGS) $(INCLUDE)

#---------------------------------------------------------------------------------
# Build rules
#---------------------------------------------------------------------------------
.PHONY: clean install

$(TARGET): $(OBJECTS)

install: $(TARGET)
	@echo INSTALL $(TARGET)
	@mkdir -p $(PORTLIBS)/lib
	@mkdir -p $(PORTLIBS)/include/SDL2
	@cp $(TARGET) $(PORTLIBS)/lib/
	@cp -f ./SDL_image.h $(PORTLIBS)/include/SDL2/

clean:
	@echo CLEAN ...
	@rm -rf $(OBJECTS) $(OBJECTS:.o=.d) $(TARGET)

#---------------------------------------------------------------------------------
# Toolchain
#---------------------------------------------------------------------------------
include $(WUT_ROOT)/share/wut.mk
LDFLAGS		+=	-L$(DEVKITPRO)/portlibs/ppc/lib
CFLAGS		+=	-I$(DEVKITPRO)/portlibs/ppc/include
CXXFLAGS	+=	-I$(DEVKITPRO)/portlibs/ppc/include
