BASEDIR	:= $(dir $(firstword $(MAKEFILE_LIST)))
VPATH	:= $(BASEDIR)

#---------------------------------------------------------------------------------
# Build options
#---------------------------------------------------------------------------------
TARGET  = libSDL2_gfx.a
SOURCES = \
	SDL2_framerate.c \
	SDL2_gfxPrimitives.c \
	SDL2_imageFilter.c \
	SDL2_rotozoom.c

OBJECTS = $(shell echo $(SOURCES) | sed -e 's,\.c,\.o,g')
INCLUDE = -I$(WUT_ROOT)/include -I$(PORTLIBS)/include -I$(BASEDIR)/../SDL2-wiiu/include

#---------------------------------------------------------------------------------
# Compile flags
#---------------------------------------------------------------------------------
CFLAGS		+=	-O2 $(INCLUDE)
CXXFLAGS	+=	-O2 $(INCLUDE)

#---------------------------------------------------------------------------------
# Build rules
#---------------------------------------------------------------------------------
.PHONY: clean install

$(TARGET): $(OBJECTS)

install: $(TARGET)
	@echo INSTALL $(TARGET)
	@mkdir -p $(PORTLIBS)/lib
	@mkdir -p $(PORTLIBS)/include/SDL2
	@cp $(TARGET) $(PORTLIBS)/lib/
	@cp -f ./SDL2_framerate.h ./SDL2_gfxPrimitives.h	./SDL2_imageFilter.h ./SDL2_rotozoom.h $(PORTLIBS)/include/SDL2/

clean:
	@echo CLEAN ...
	@rm -rf $(OBJECTS) $(OBJECTS:.o=.d) $(TARGET)

#---------------------------------------------------------------------------------
# Toolchain
#---------------------------------------------------------------------------------
include $(WUT_ROOT)/share/wut.mk
LDFLAGS		+=	-L$(DEVKITPRO)/portlibs/ppc/lib
CFLAGS		+=	-I$(DEVKITPRO)/portlibs/ppc/include
CXXFLAGS	+=	-I$(DEVKITPRO)/portlibs/ppc/include
