#---------------------------------------------------------------------------------
# Setup compile environment
#---------------------------------------------------------------------------------
$(call assert,$(call seq,$(strip $(DEVKITPPC)),),Please set DEVKITPPC in your environment.)
$(call assert,$(call seq,$(strip $(WUT_ROOT)),),Please set WUT_ROOT in your environment.)
export PORTLIBS := $(DEVKITPRO)/portlibs/ppc
export PATH := $(WUT_ROOT)/bin:$(DEVKITPPC)/bin:$(PORTLIBS)/bin:$(PATH)
AS  = powerpc-eabi-as
CC  = powerpc-eabi-gcc
CXX = powerpc-eabi-g++
AR  = powerpc-eabi-ar


#---------------------------------------------------------------------------------
# Build options
#---------------------------------------------------------------------------------
TARGET  = libSDL2_ttf.a
SOURCES = \
	SDL_ttf.c

OBJECTS = $(shell echo $(SOURCES) | sed -e 's,\.c,\.o,g')
INCLUDE = -I$(WUT_ROOT)/include -I$(PORTLIBS)/include -I$(PORTLIBS)/include/SDL2 -I$(PORTLIBS)/include/freetype2


#---------------------------------------------------------------------------------
# Compile flags
#---------------------------------------------------------------------------------
CFLAGS   := -O2 -D__WIIU__ -D__WUT__ -mcpu=750 -meabi -mhard-float $(INCLUDE)
CXXFLAGS := $(CFLAGS)
ASFLAGS  := -g


#---------------------------------------------------------------------------------
# Build rules
#---------------------------------------------------------------------------------
.PHONY: clean install
$(TARGET): $(OBJECTS)
	rm -f $@
	$(AR) rcs $@ $^
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@
%.o: %.m
	$(CC) $(OBJCFLAGS) -c $< -o $@
%.o: %.s
	$(CC) -x assembler-with-cpp $(ASFLAGS) -c $< -o $@
%.o: %.S
	$(CC) -x assembler-with-cpp $(ASFLAGS) -c $< -o $@
install: $(TARGET)
	mkdir -p $(PORTLIBS)/lib
	mkdir -p $(PORTLIBS)/include/SDL2
	cp $(TARGET) $(PORTLIBS)/lib/
	cp -f ./SDL_ttf.h $(PORTLIBS)/include/SDL2/
clean:
	rm -rf $(OBJECTS) $(TARGET)