BASEDIR	:= $(dir $(firstword $(MAKEFILE_LIST)))
VPATH	:= $(BASEDIR)

#---------------------------------------------------------------------------------
# Build options
#---------------------------------------------------------------------------------
TARGET  = libSDL2_mixer.a
SOURCES = $(wildcard ./*.c)

OBJECTS = $(SOURCES:.c=.o)
INCLUDE = -I$(WUT_ROOT)/include -I$(PORTLIBS)/include -I$(PORTLIBS)/include/SDL2

#---------------------------------------------------------------------------------
# Compile flags
#---------------------------------------------------------------------------------
BUILDFLAGS	+=	-DMUSIC_WAV -DMUSIC_OGG -DOGG_USE_TREMOR -DMUSIC_MP3_MPG123
CFLAGS		+=	-O2 $(BUILDFLAGS) $(INCLUDE)
CXXFLAGS	+=	-O2 $(BUILDFLAGS) $(INCLUDE)

#---------------------------------------------------------------------------------
# Build rules
#---------------------------------------------------------------------------------
.PHONY: clean install

$(TARGET): $(OBJECTS)

install: $(TARGET)
	@echo INSTALL $(TARGET)
	@mkdir -p $(PORTLIBS)/lib
	@mkdir -p $(PORTLIBS)/include/SDL2
	@cp $(TARGET) $(PORTLIBS)/lib/
	@cp -f ./SDL_mixer.h $(PORTLIBS)/include/SDL2/

clean:
	@echo CLEAN ...
	@rm -rf $(OBJECTS) $(OBJECTS:.o=.d) $(TARGET)

#---------------------------------------------------------------------------------
# Toolchain
#---------------------------------------------------------------------------------
include $(WUT_ROOT)/share/wut.mk
LDFLAGS		+=	-L$(DEVKITPRO)/portlibs/ppc/lib
CFLAGS		+=	-I$(DEVKITPRO)/portlibs/ppc/include
CXXFLAGS	+=	-I$(DEVKITPRO)/portlibs/ppc/include